### ISSUE TITLE
Do not indent lines without selection

### ISSUE THREAD

**Issue by arcanis** [julianlam/tabIndent.js#10]
Most of the time, when I want to indent a code block, I go to the start of the first line, hold shift, and press 'down' for each line to indent. However, when doing this here, it will also indent the next line, even if there is nothing selected in it.

I suggest to check if there is multiple lines and, if there is, do not indent the last line it doesn't contain any selection.

**Comment by julianlam** [comment]
Thanks for the bug report. The way selection is handled by tabIndent.js, you're technically on the next line, hence it is tabbed as well. However I do see the UX problem. This should be an easy fix.

**Comment by julianlam** [comment]
Fixed in commit 0a959567d05b2aae3dfab86b265cf7c181ad2625

**Comment by julianlam** [comment]
Got to love those two-character bug fixes...!
