### ISSUE TITLE
bugs in function render() 

### ISSUE THREAD

**Issue by yqt** [julianlam/tabIndent.js#14]
Hi, I am writing a GM script with tabIndent.js and just using the function render() simply . But  my browser consumes more and more CPU when I click the TEXTAREA then other element alternately again and again. After some tracing works, I think there is some bugs in function render().

Take the demo given in the project as a example. 
Put "console.log("rendering");" in tabIndent.js:152(right above "if (el.nodeName === 'TEXTAREA')") and open index.html then do the same thing mentioned above, we get:
## Console:

[14:04:54.511] rendering @ file:///D:/Users/Theodore/Desktop/tabIndent.js-master/js/tabIndent.js:152 (run once)
[14:04:57.150] rendering @ file:///D:/Users/Theodore/Desktop/tabIndent.js-master/js/tabIndent.js:152 (run twice)
[14:05:00.094] rendering @ file:///D:/Users/Theodore/Desktop/tabIndent.js-master/js/tabIndent.js:152 (run 4 times)
[14:05:02.047] rendering @ file:///D:/Users/Theodore/Desktop/tabIndent.js-master/js/tabIndent.js:152 (run 8 times)
[14:05:03.351] rendering @ file:///D:/Users/Theodore/Desktop/tabIndent.js-master/js/tabIndent.js:152 (run 16 times)
[14:05:15.278] rendering @ file:///D:/Users/Theodore/Desktop/tabIndent.js-master/js/tabIndent.js:152 (run 32 times)
...
## 

Same problem happens under Chrome and FF. Any ideas?

**Comment by Geven7** [comment]
I am so sorry.i have no idea.

**Comment by yqt** [comment]
## tabIndent.js:

<pre>
...
178: 178:     el.addEventListener('blur', function b(e) {
179: 179:           self.events.disable(e);
     180: +         el.removeEventListener('blur', b);
180: 181:     });
...
</pre>

## 

seems to fix the bug.

**Comment by yqt** [comment]
prevent duplicate classname.

## tabIndent.js:

<pre>
...
164: 164:     if (contains !== -1) classes.splice(contains, 1);
165:      -   classes.push('tabIndent-rendered');
     165: +   if (classes.indexOf('tabIndent-rendered') == -1) classes.push('tabIndent-rendered');
166: 166:     el.setAttribute('class', classes.join(' '));
...
212: 213:     if (contains !== -1) classes.splice(contains, 1);
213:      -   classes.push('tabIndent');
     214: +   if (classes.indexOf('tabIndent') == -1) classes.push('tabIndent');
214: 215:     el.setAttribute('class', classes.join(' '));
...
</pre>

##

**Comment by julianlam** [comment]
Thank you both for your efforts, I'll review this in an hour or so and get back to you.

**Comment by julianlam** [comment]
Hi yqt, it looks like I was sloppy with my event adding and removing. While the end result is the same (the tab key is only captured once), there does seem to be a slight memory issue.

I applied your fix, and while that stopped the duplicate class names from appearing, the issue still persists. Can you verify that the memory leak issue still exists? Upon testing, my "focus" handler still keeps getting added.

**Comment by yqt** [comment]
I just test the demo with the fixes of comment 2&3.

It seems that the memory leak issue no longer exists if you operate in a regular way(wait for the background image of TEXTAREA to show up before clicking another element) through the figure showed in the timeline tool of Chrome.(HERE: http://i.imgur.com/JMcRE.png ).The blue line indicates the amount of eventListeners at a time.When I stop clicking the TEXTAREA and other element alternately the amount of listeners will back to 2.

But when I click very fast or extend delay of setTimeout,the listeners will increase rapidly.I think that may have sth. to do with the code between L:155 to L:175 because the ‘blur’ event will trigger both of the 2 handlers and the timer won't be fired as expected. That means some ‘focus’ handler won't be removed.

For index page with renderall() the code runs like:

<pre>
(open index.html)
...
154:         el.addEventListener('focus', function f() {...}); // not fired; TEXTAREA is not on focus
...
178:         el.addEventListener('blur', function b(e){...}; 
...
(click TEXTAREA)
...
155:         var delayedRefocus = setTimeout(function() {...}, ...); // timeoutID:1
...
172:         el.addEventListener('blur', function b(){...});
...
(click other ele. before timeout)
...
179:         self.events.disable(e); // 'blur' handler at L:178 fired;
...
154:         el.addEventListener('focus', function f() {...}); // re-render
...
178:         el.addEventListener('blur', function b(e){...};  // next handler of L:178
...
     180:    el.removeEventListener('blur', b); // 'blur' listener at  L:178 removed
...
173:         clearTimeout(delayedRefocus); // clear timeoutID:1,but it doesn't fire the timeout event here for some reason.So the next setTimeout will overwrite the timeID and the previous 'focus' handler won't be removed.
...
174:         el.removeEventListener('blur', b); // 'blur' listener at L:172 removed
...
</pre>

Exactly I not quite sure since I haven't read all of your code thoroughly.

Rewrite the field of setTimeout and first 'blur'  may be a good idea to solve this issue.

**Comment by julianlam** [comment]
As it turns out, the bug wasn't in the `render()` function, but just that when I removed the enhancement `onBlur`, I didn't need to re-add the event at all. The latest version should resolve this issue.
