### ISSUE TITLE
Remove unnecessary addEventListener polyfill

### ISSUE THREAD

**Issue by wjbryant** [julianlam/tabIndent.js#16]
While comparing my project ([taboverride](https://github.com/wjbryant/taboverride)) with tabIndent, I noticed that tabIndent includes an `addEventListener` polyfill even though it doesn't support IE <9. Removing the polyfill will reduce the file size by nearly 25% without affecting functionality.

By the way, nice project! This is the most popular implementation of tab-enabled textareas I've seen. It's always interesting to see the same problem solved in different ways.

**Comment by julianlam** [comment]
Thanks for the kind words -- the aim of tabIndent.js is to be completely browser-compatible (although obviously, within limits). Instead of removing the polyfill, I'd be more inclined to instead update the library so that it works on all browsers.

I just don't happen to have IE6 kicking around anymore ;) (nor a BrowserStack subscription)

**Comment by wjbryant** [comment]
As far as I know, the only way to support IE 6-8 is to use a `TextRange` object created from the selection: `document.selection.createRange()`. There's some good info on working with ranges at [quirksmode.org](http://www.quirksmode.org/dom/range_intro.html) and [msdn](http://msdn.microsoft.com/en-us/library/ie/ms535872.aspx), although I'm not sure if everything documented on msdn is supported in older versions of IE.

Testing in older versions of IE is a pain. I run a virtual machine and use the [images provided by Microsoft](http://www.microsoft.com/en-us/download/details.aspx?id=11575) for IE testing.

**Comment by julianlam** [comment]
Hi wjbryant - having played around with ranges myself in the past, I'm not keen to do so again... perhaps I _will_ remove the `addEventListener` polyfill after all...

**Comment by wjbryant** [comment]
Yeah, it can be really frustrating. There's not really any harm in removing it for now, since it can always be added back in if you change your mind.

-Bill
