### ISSUE TITLE
Base64 encode the active.png icon

### ISSUE THREAD

**Issue by cascornelissen** [julianlam/tabIndent.js#17]
Wouldn't it be better to base64 encode the little icon? It will cut down on requests and users won't have to look into their folder structure to make sure the icon is accessible.

**Comment by julianlam** [comment]
You're correct, of course. I'll make the change sometime today :+1:

**Comment by cascornelissen** [comment]
Thanks for the response!

It was the first time I opened an issue on GitHub so it's nice to get a reponse! Good luck with the fix.
