### ISSUE TITLE
Issue with Init On Focus

### ISSUE THREAD

**Issue by roydukkey** [julianlam/tabIndent.js#18]
``` javascript
$(".tab-indent").one("focus", function () {
    var g = $(this).height(350)
    tabIndent.render(g[0])
})
```

It seems there is a issue where the textarea doesn't have tabIndent.js applied until after the user focuses the element for a second time.

I understand I could add the height via `tabIndent-rendered { min-height: 350px }`, but here I used it to show the event is triggered without applying tabIndent.js.

**Comment by julianlam** [comment]
Hey roydukkey,

Thanks for the issue report. It looks like you are utilising the `render` handler incorrectly, as it is designed to be invoked prior to user action, as opposed to during a user focus event.

In other words, try invoking `tabIndent.render()` on `$(document).ready()` instead. Once `render` is called on an element, it persists indefinitely until you call `remove`, if you choose to.

Please refer to [this jsFiddle](http://jsfiddle.net/vRjcr/) for the usage pattern I am referring to.

**Comment by roydukkey** [comment]
I don't want all fields to render when the document is ready, but rather when the user has interacted with them. How can this functionality be obtained?
