### ISSUE TITLE
shift+tab may be limited

### ISSUE THREAD

**Issue by yule2001** [julianlam/tabIndent.js#20]
when the cursor ‘ left has something input,then press shift+tab does not works.
I input "a",then press tab , it wors well, and press shift+tab , it works too.But when press tab and input "1",the cursor on the right of "1",then press shift+tab ,it does not works. (firefox and chrom newest version)

**Comment by julianlam** [comment]
Hello @yule2001 -- thanks for the report. This is intended behaviour, as I did not want the line's identation to be changed if the cursor is not at the beginning of the line. If the editor looks as follows:

```
1|
```

... with the `|` as the cursor, then pressing shift-tab should _erase_ tabs until it encounters a character. What sort of behaviour were you expecting to see? :smile:

**Comment by yule2001** [comment]
Thanks
