### ISSUE TITLE
License Type?

### ISSUE THREAD

**Issue by ghost** [julianlam/tabIndent.js#8]

**Comment by julianlam** [comment]
Hi Hirvesh,

Most likely MIT, although I'll have to look into license types at a later date. Basically, free for use in open-source and proprietary software. Linkbacks (in code) would be nice, but are not required.

Basically, don't worry about it.

**Comment by ghost** [comment]
Hi Julian,

Thank you for the update!  Made a blog post about it here: http://functionn.blogspot.com/2012/11/tabindentjs-javascript-library-for-tab.html and posted it to Hacker News (http://news.ycombinator.com/item?id=4854933) too and it got to the frontpage.  I hope it sent some visitors your way and made people more aware of your nice project :)

**Comment by julianlam** [comment]
Came back from Christmas shopping to twice as many stars. Thank you so much for spreading the word!

**Comment by ghost** [comment]
my pleasure! Merry Christmas, wayyyyyy beforehand :)
